---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      #access_log  /var/log/nginx/host.access.log  main;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      #error_page  404              /404.html;
      # redirect server error pages to the static page /50x.html
      
      error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    server: web
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
        server: web
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: default
          mountPath: "/etc/nginx/conf.d"
          readOnly: true
      volumes:
      - name: default
        configMap:
          name: nginx
status: {}

---
apiVersion: v1
kind: Service
metadata:
     name: nginx
spec:
     type: NodePort
     selector:
          app: nginx
     ports:
         - port: 8080
           targetPort: 80
           nodePort: 31500